[settings]
experimental = true
jobs = 1

[tools]
rust = "nightly"
"cargo:cargo-nextest" = "latest"
cmake = "latest"

[task_config]
includes = [
    "tasks/format.toml",
    "tasks/linting.toml",
    "tasks/check.toml",
    "tasks/fixes.toml",
    "tasks/tests.toml",
    "tasks/run.toml",
    "tasks/misc.toml",
    "tasks/eval.toml",
    "tasks/build.toml"
]
