#:schema https://mise.jdx.dev/schema/mise-task.json

["lint:crates"]
description = "Check all rust crates"
usage = """
flag "--fix" env="STOP_LINT_FIX" help="Apply all lint suggestions"
flag "--allow-dirty" env="STOP_LINT_FIX_DIRTY" help="Allow dirty working directory"
"""
run = '''
cargo clippy --workspace --all-targets{{ " --fix" if usage.fix else "" }}{{ " --allow-dirty" if usage.allow_dirty and usage.fix else "" }}
'''
